version: '2.4'
services:
  prometheus:
    image: "prom/prometheus:v2.26.0"
    container_name: prometheus
    # REPLACE LOCALHOST WITH THE SERVER IP IF YOU WILL ACCESS IT FROM ANOTHER SERVER
    hostname: localhost
    restart: unless-stopped
    mem_limit: 4G
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - "./prometheus/:/etc/prometheus/"
      - "prometheus_data:/prometheus"
    networks:
      - "monitoring"
  node-exporter:
    image: "prom/node-exporter:v1.1.2"
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
     - "monitoring"
  grafana:
    image: "grafana/grafana:7.5.2"
    container_name: grafana
    restart: unless-stopped
    mem_limit: 4G
    ports:
      - "80:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
    networks:
      - monitoring
    environment:
      # INSTALL SOME GRAFANA PLUGINS AUTOMATICALLY
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,novalabs-annotations-panel,vonage-status-panel,fetzerch-sunandmoon-datasource,natel-discrete-panel,natel-influx-admin-panel
      # YOU CAN CHANGE THE ADMIN PASSWORD USING THIS VARIABLE
      - GF_SECURITY_ADMIN_PASSWORD=admin
  alertmanager:
    image: "prom/alertmanager:v0.21.0"
    container_name: alertmanager
    restart: unless-stopped
    mem_limit: 4G
    ports:
      - "9093:9093"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    volumes:
      - "./alertmanager/:/etc/alertmanager/"
      - "alertmanager_data:/alertmanager"
    networks:
      - "monitoring"
  custom-exporter:
    build: "customexporter"
    container_name: customexporter
    restart: unless-stopped
    ports:
     - "5000:5000"
    networks:
     - "monitoring"
volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:
networks:
  monitoring:
