# Global Configuration
global:
    smtp_smarthost: 'smtp.gmail.com:587'
    smtp_from: 'email@mail.com'
    smtp_auth_username: 'email@mail.com'
    smtp_auth_identity: 'email@mail.com'
    smtp_auth_password: 'password'
    smtp_require_tls: true
  
# The root node of the routing tree.
route:
  group_by: ['severity']
  # When a new group of alerts is created by an incoming alert, wait at least 'group_wait' to send the initial notification
  group_wait: 30s
  # When the first notification was sent, wait 'group_interval' to send a batch of new alerts
  group_interval: 1m
  # If an alert has successfully been sent, wait 'repeat_interval' to resend them
  repeat_interval: 6h
  # Default receivers
  receiver: 'email'

# Inhibition rules allow to mute a set of alerts given that another alert is firing.
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'

# Receivers details (email, slack, integrations configs, etc)
receivers:
  - name: 'email'
    email_configs:
    - to: 'email@mail.com'