# Global configuration
global:
  # How frequently to scrape targets by default.
  scrape_interval:     15s
  # How long until a scrape request times out.
  scrape_timeout: 10s
  # How frequently to evaluate rules.
  evaluation_interval: 15s 

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['alertmanager:9093']
    
# Alerts rules
rule_files:
  - 'alerts.yml'

# A list of scrape configurations.
scrape_configs:
  # The job name assigned to scraped metrics by default.
  - job_name: 'prometheus'
    # List of labeled statically configured targets for this job.
    static_configs:
    # The targets specified by the static config.
    - targets: ['localhost:9090']

  - job_name: 'My Targets'
    file_sd_configs:
      - files:
         - targets.yml

  - job_name: 'My Exporter'
    file_sd_configs:
      - files:
         - custom-exporter.yml